# 工作流名称
name: Deploy to Vercel

# 触发条件：当 main 分支收到推送时
on:
  push:
    branches: [main]

jobs:
  deploy:
    # 指定运行环境为最新版 Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 步骤1：检出代码
      - uses: actions/checkout@v3

      # 步骤2：设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # 使用 Node.js 18.x

      # 步骤3：安装 pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # 使用 pnpm 8.x

      # 步骤4：安装项目依赖
      - name: Install Dependencies
        run: pnpm install

      # 步骤5：构建项目
      - name: Build
        run: pnpm docs:build

      # 步骤6：部署到 Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          # Vercel 部署令牌
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          # Vercel 组织 ID
          vercel-org-id: ${{ secrets.ORG_ID }}
          # Vercel 项目 ID
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          # 工作目录
          working-directory: ./
# 6YMCD6MQHjofdIxzpoNV32Di
